import { createSlice } from "@reduxjs/toolkit";

const teamInfoSlice=createSlice({
    name:"teaminfo",
    initialState:{
        team1Info:[
            {
                    id:0,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:1,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:2,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:3,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:4,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:5,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:6,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:7,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },{
                    id:8,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:9,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:10,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:11,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                }
        ],
        team2info:[
            {
                    id:0,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:1,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:2,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:3,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:4,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:5,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:6,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:7,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },{
                    id:8,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:9,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:10,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                },
                {
                    id:11,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                }
        ],
        toss:{
            team:'',
            chossto:'',
        }
    },
    reducers:{
        addteam1:(state,action)=>{
            state.team1Info=[];
            for(let i=1;i<=action.payload;i++){
                state.team1Info.push({
                    id:i,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                })
            }
        },
        updateuserName:(state,action)=>{
            const {index,value}=action.payload;
            const plyerinfo=state.team1Info[index];
            plyerinfo.playerName=value;
        },
        addteam2:(state,action)=>{
            state.team2info=[];
            for(let i=1;i<=action.payload;i++){
                state.team2info.push(
                {
                    id:i,
                    playerName:'',
                    four:0,
                    six:0,
                    runs:0,
                    wicket:0,
                    over:0
                }
                )
            }
            
        },
        updateuserNameteam2:(state,action)=>{
            const {index,value}=action.payload;
            state.team2info[index].playerName=value;
        },
        updateToss:(state,action)=>{
            const {key,value}=action.payload;
            state.toss[key]=value;
        }


    }
});
export default teamInfoSlice.reducer;
export const {addteam1,updateuserName,addteam2,updateuserNameteam2,updateToss}=teamInfoSlice.actions